# Generated by Django 4.0.6 on 2022-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('score', models.PositiveSmallIntegerField()),
                ('time', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
